export const TOKEN = 'token'
export const IS_CORRECT_USER_PROFILE = 'isCorrectUserProfile'
export const CHECKED_REPOSITORIES = 'checkedRepositories'
export const IS_NOT_BRANCH_FIXED = 'isNotBranchFixed'
export const CHANGED_BRANCH_REPOSITORIES = 'changedBranchRepositories'
export const BRANCH = 'branch'
export const SELECTED_FILE_TYPE = 'selectedFileType'
export const SELECTED_DATA_GROUP_TYPE = 'selectedDateGroupType'